# Generated by Django 5.0.7 on 2024-08-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED'), ('PENDING', 'PENDING')], max_length=50),
        ),
    ]
