# Generated by Django 5.0.7 on 2024-08-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurant', '0002_alter_table_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_no',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
