# Generated by Django 5.0.7 on 2024-08-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurant', '0002_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
    ]
