# Generated by Django 5.0.7 on 2024-08-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurant', '0003_remove_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='table',
            name='availability_status',
            field=models.CharField(choices=[('OCCUPPIED', 'OCCUPPIED'), ('AVAILABLE', 'AVAILABLE')], max_length=20),
        ),
    ]
